### ISSUE TITLE
[FE] Re-implement search for listings

### ISSUE THREAD

**Issue by Kalsyc** [Project-Kampong/kampong-backend#192]
- Need search for listings based on title/name, category and location
- For now, we need an OR search due to low number of listings. However, in the future, we may switch to AND search
- Currently, location is located in a separate table, and each listing can have multiple locations
- Locations of the listings must also be given in the data to the FE so that it can be shown on the listing card

**Comment by Kalsyc** [comment]
Likely that i will store the title input as a string and the category/location as an array in the FE, will be great if i can somehow place them as query parameters in the API call like how most websites do it.

Maybe something like search_query?input=sometitle&cat=healthcare&location=Sembawang

**Comment by don-tay** [comment]
See https://stackoverflow.com/questions/2514548/how-to-search-multiple-columns-in-mysql
for fuzzy search on multiple columns with sql

**Comment by don-tay** [comment]
@Kalsyc @derrickSP 
Here is a draft API contract so that you can start building FE towards this API:
Search listings by Title, Category and Location
Route: `/api/listings/search`
Access: Public

Query params
`query` - keyword to be searched for, multiple keywords delimited by single comma
`limit` - Number of results to display. Default: 10

Example query: `/api/listings/search?query=Project,Jurong,East`
```
200 OK
{
    "success": true,
    "data": [
        {
            "listing_id": "1276b4eb-df3a-4de3-bcae-a450ed96eeac",
            "organisation_id": null,
            "created_by": "b7662cd1-a2c9-4054-95e7-078e35ea6fa1",
            "title": "Project Kampong",
            "category": "Technology",
            "about": null,
            "tagline": "With Kampong you can",
            "location": "Jurong",
            "mission": "To build a platform that connects people with ideas and skills to build and track social good project initiatives",
            "listing_url": "www.test.com",
            "pic1": "https://kampong-dev.s3.ap-southeast-1.amazonaws.com/kampong%20logo-1597985636566.jpeg",
            "pic2": "https://kampong-dev.s3.ap-southeast-1.amazonaws.com/group-large-1597985817857.png",
            "pic3": null,
            "pic4": null,
            "pic5": null,
            "is_published": false,
            "is_verified": false,
            "start_date": "2020-08-20T20:50:15.048Z",
            "end_date": null,
            "created_on": "2020-08-20T20:50:15.048Z",
            "deleted_on": null
        }
    ]
}
```

**Comment by Kalsyc** [comment]
Jurong, East? So 'East' will bring out Tampines..? or...

**Comment by don-tay** [comment]
Using elasticsearch: https://www.digitalocean.com/community/tutorials/how-to-build-a-real-time-search-engine-with-node-vue-and-elasticsearch

**Comment by don-tay** [comment]
> Jurong, East? So 'East' will bring out Tampines..? or...

East will bring out Jurong East, not Tampines

**Comment by don-tay** [comment]
SQL full text search: https://www.compose.com/articles/mastering-postgresql-tools-full-text-search-and-phrase-search/

**Comment by Kalsyc** [comment]
Ahh ok okay, then can. 👍🏻 
So for the API call, i just need to append all the categories/location/search input in `query` right?
