### ISSUE TITLE
Bug : Empty body when using /api/send-email

### ISSUE THREAD

**Issue by ahliang51** [Project-Kampong/kampong-backend#241]
Hi, 

Currently, I am trying to send an email to the listing's owner when a user applies for a role. However, when I am trying to use the email endpoint, the body of the email is actually blank. 

![image](https://user-images.githubusercontent.com/15278497/98460348-9919e700-21de-11eb-8a02-14bd63340d68.png)
![image](https://user-images.githubusercontent.com/15278497/98460406-21988780-21df-11eb-9138-7d1b9144507e.png)

On the frontend side, the values that I am sending for the subject & message actually contain some value. I validated this by console logging it and check whether any values are being printed out. 

Have tried sending multiple times but the body still contains empty. 

Think the error is due to the following screenshot. 
![photo_2020-11-08_16-29-07](https://user-images.githubusercontent.com/15278497/98460458-9d92cf80-21df-11eb-8406-53fc00b00584.jpg)

the property message is spelled incorrectly. 

@don-tay

**Comment by don-tay** [comment]
thank you for raising this, it is fixed in #242
