### ISSUE TITLE
[P1] Implement hashed serial for listings and profile id

### ISSUE THREAD

**Issue by don-tay** [Project-Kampong/kampong-backend#80]

**Comment by don-tay** [comment]
@Kalsyc What are your thoughts?

Problem:
1. Not to expose the `listing_id` and `profile_id` for get single listing and get single profile

Implementation:

Approach 1:
Add a column to user, profile and listings: `user_uid` and `profile_uid`, for ONLY get single listing and get single profile endpoints.
+: This new endpoints can be implemented alongside existing ones. Does not affect existing logic except the 2 endpoints.
-: May be confusing(?) as an endpoint, due to usage of both `user_id` and user_uid` fields for different endpoints now.
Relies on implementation of PL/pgSQL triggers/functions, and thus, not easily understood on the backend.
May be considered data redundancy for having both `id` and `uid` fields

Approach 2:
Use a uuid generator for `user_id` and `listings_id`, generated from backend and inserted into db each time.
(see: [https://www.npmjs.com/package/uuid#uuidv4options-buffer-offset](uuidv4)
+: More streamlined flow from backend to db, with backend carrying bulk of logic.
-: Mock data population is a little tricky, especially with managing foreign keys, these uuid needs to be copy pasted manually. Will use fewer mock data with this method.

**Comment by Kalsyc** [comment]
We can try: [hashids.js](https://github.com/niieani/hashids.js) which is a combination of both Approach 1 and 2. 

The idea is we try to keep db-level stuff the same but we hash the value of the id in the main GET, then when we want to retrieve data, we unhash the value and retrieve from the db.

**Comment by derrickSP** [comment]
Hi, its not really a matter of not exposing the listing_id and profile_id, just randomise the IDs such that people can't tell the number of listings/ profiles on the site.

- Using random ID instead of incremental approach

**Comment by Kalsyc** [comment]
That works too, whichever implementation is easier. But I think if we don't wanna touch the db, then hash and un-hash is the way to go.
